#!/python3
from colorama import Fore, Back, Style

MAX_RECV_DATA = 1024

MAX_QUEUED_REQUESTS = 10

INIT_IP = "127.0.1.1"
INIT_PORT = 4043

IP_REGEX = "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"

ITEM = "item"
CONTENT = "content"
STATUS = "status"

CHECK_MSG_INTERVAL = 5

ENC_DATA_FORMAT = "utf-8"

NOT_FOUND_MSG = "404 NOT FOUND"
OK_MSG = "OK"

DELIM_SERVERS_LIST = " --> "

RESET_COLOR = Style.RESET_ALL
IP_COLOR = Fore.MAGENTA
PORT_COLOR = Fore.CYAN
INFO_COLOR = Fore.GREEN
RECV_COLOR = Fore.LIGHTCYAN_EX
SEND_COLOR = Fore.BLUE
ERROR_COLOR = Fore.RED
WARN_COLOR = Fore.YELLOW

CREATOR = "creator"
DATA = "data"
MSG_TYPE = "type"
MSG_STRUCT = "struct"
FN = "fn"

INSERT_MSG = "INSERT"
UPDATE_MSG = "UPDATE"
CHECK_MSG = "CHECK"
GET_MSG = "GET"
PUT_MSG = "PUT"
FORWARD_GET_MSG = "FORWARD_GET"
FORWARD_PUT_MSG = "FORWARD_PUT"
RESPONSE_GET_MSG = "RESPONSE_GET"
RESPONSE_PUT_MSG = "RESPONSE_PUT"

MSG_TYPES = [
    INSERT_MSG,
    UPDATE_MSG,
    CHECK_MSG,
    GET_MSG,
    PUT_MSG,
    RESPONSE_GET_MSG,
    RESPONSE_PUT_MSG,
    FORWARD_GET_MSG,
    FORWARD_PUT_MSG,
]
